language: ruby
os:
- linux
dist: xenial
services:
- docker
script:
- wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
- chmod +x latexdockercmd.sh
- "./latexdockercmd.sh pdflatex tex/OE.tex"
deploy:
  provider: releases
  api_key:
    secure: PAT
  file:
    - OE.pdf
  skip_cleanup: true